name = "porukice-api"
main = "worker.js"
compatibility_date = "2026-07-06"

[vars]
ALLOWED_ORIGIN = "https://aaabawgte.github.io"
JWT_SECRET = "promijeni-ovo-u-cloudflare-secret"
VAPID_PUBLIC_KEY = "BG_zjrCpUPYCw8rFNqZj5xwuLBx7FswntEH_KlY64NwY1psf9PVaY0smnRs5flRG5l2z_ek8pkGavlpHtDbNgUM"
VAPID_SUBJECT = "mailto:bruno@example.com"

[[d1_databases]]
binding = "DB"
database_name = "porukice-db"
database_id = "0b7f210c-c0cf-4d18-8f82-2f5b8313b21e"